// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAma3He31wOnxfi8mFxSnCQtOatO0PV_uc',
    appId: '1:377954419408:web:acf5ecba6a88c2949f94d5',
    messagingSenderId: '377954419408',
    projectId: 'sales-expense-tracker-daab9',
    authDomain: 'sales-expense-tracker-daab9.firebaseapp.com',
    storageBucket: 'sales-expense-tracker-daab9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXEs5TueDoysrMk373lPqPFl-YDBZhGXE',
    appId: '1:377954419408:android:98ccf76c6d2826e89f94d5',
    messagingSenderId: '377954419408',
    projectId: 'sales-expense-tracker-daab9',
    storageBucket: 'sales-expense-tracker-daab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu3ty0NPuRfot6VqZBbrP0H-RTAdfAxhU',
    appId: '1:377954419408:ios:2ddcf58bfa2a23b69f94d5',
    messagingSenderId: '377954419408',
    projectId: 'sales-expense-tracker-daab9',
    storageBucket: 'sales-expense-tracker-daab9.firebasestorage.app',
    iosClientId: '377954419408-ok7nn0ivpkva08srkv94bq0re4s322hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu3ty0NPuRfot6VqZBbrP0H-RTAdfAxhU',
    appId: '1:377954419408:ios:2ddcf58bfa2a23b69f94d5',
    messagingSenderId: '377954419408',
    projectId: 'sales-expense-tracker-daab9',
    storageBucket: 'sales-expense-tracker-daab9.firebasestorage.app',
    iosClientId: '377954419408-ok7nn0ivpkva08srkv94bq0re4s322hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAma3He31wOnxfi8mFxSnCQtOatO0PV_uc',
    appId: '1:377954419408:web:fd883cf917f6b5909f94d5',
    messagingSenderId: '377954419408',
    projectId: 'sales-expense-tracker-daab9',
    authDomain: 'sales-expense-tracker-daab9.firebaseapp.com',
    storageBucket: 'sales-expense-tracker-daab9.firebasestorage.app',
  );
}
